#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/2af82157-0a99-4086-9d05-ed884a93a8df/ # 
title: Retail API 
description: This API returns, creates, updates & deles product, product category and bills.
#Developed by Ashenafi E. 
#Project Manager: Henok 
#Craft Software, April 2020.
securitySchemes:
  basic:
    description: |
      This API supports Basic Authentication.
    type: Basic Authentication 
types:
  productDataType: !include dataTypes/productDataType.raml
  productCategoryDataType: !include dataTypes/productCategoryDataType.raml
  bilDataType: !include dataTypes/billDataType.raml
traits:
  getresponse: !include traits/getResponse.raml
  postResponse: !include traits/postResponseTrait.raml
  putResponse: !include traits/putResponse.raml
  deleteResponse: !include traits/deleteResponse.raml
/product:
  get:
    description: Fetches all products.
    responses:
     200:
       body:
          application/json:
            type: productDataType
            example: !include examples/productExample.raml
    is:
      - getresponse:
  post:
    description: Creates a new product. 
    body:
      application/json:
    responses:
    is:
      - postResponse 
  /{productID}:
    uriParameters:
      productID:
        type: integer
    get:
      description: Fetches a specific product.
      responses:
       200:
        body:
          application/json:
            type: productDataType
            example: !include examples/productExample.raml
    is:
      - getresponse:
    put:
      description: Updates product.
      body:
       application/json:
      responses:
      is:
        - putResponse 
    delete:
      description: Deletes prodcut by ID
      body:
        application/json:
      responses:
      is:
       deleteResponse 
/bills:  
  displayName: Bills
  description: Fetches all bill data
  get:
    responses:
      200:
        body:
          application/json:
            type: bilDataType
            example:
              !include examples/billExample.raml 
  post:
    description: Creates a a bill id
    body:
      application/json:
    is:
      - postResponse
  /{billID}:
    uriParameters:
      billID:
        type: integer
    get:
      description: Fetches bills of a particular id.
      responses:
        200:
          body:
            application/json:
              type: bilDataType
              example:
                !include examples/billExample.raml
    put:
      description: Updates bill data.
      body:
        application/json:
      responses:
      is:
        - putResponse 
    delete:
      description: Deletes bill from the system.
      body:
        application/json:
      responses:
      is:
        - deleteResponse 
/productCategory:
  displayName: Product Category
  get:
    description: Feches list of all product category data
    responses: 
      200:
        body:
          application/json:
            type: productCategoryDataType
            example: !include examples/productCategoryExample.raml
  post:
    description: Creates a new product category.
    body:
      application/json:
    responses:
    is:
      - postResponse 
  /{productCategoryID}:
    uriParameters:
      productCategoryID:
        type: integer
    displayName: Product ID
    get:
      description: Fetches a specific product category
      responses:
       200:
         body:
            application/json:
              type: productCategoryDataType
              example: !include examples/productCategoryExample.raml
    put:
      description: Updates a product category.
      body:
        application/json:
      responses:
      is:
        - putResponse 
    delete:
      description: Removes an existing product category
      body:
        application/json:
      responses:
      is:
        - deleteResponse

